#version 460 core

layout(isolines, equal_spacing, cw) in;

uniform float CYCLE_TIME_SECS = 0;

//
// Transformation matrices
//

mat4 translate(vec3 v)
{
    return mat4(
        1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0,
        v.x, v.y, v.z, 1.0
    );
}

mat4 perspective(float fov_rads, float aspect, float znear, float zfar)
{
    float f = 1.0 / tan(fov_rads / 2.0);
    return mat4(
        f / aspect, 0.0, 0.0, 0.0,
        0.0,        f,   0.0, 0.0,
        0.0,        0.0, (zfar + znear)/(znear - zfar), -1.0,
        0.0,        0.0, (2.0 * zfar * znear)/(znear - zfar), 0.0
    );
}

mat4 x_rotation(float rads)
{
    float c = cos(rads);
    float s = sin(rads);

    return mat4(
        1.0, 0.0, 0.0, 0.0,
        0.0, c,   s,   0.0,
        0.0, -s,  c,   0.0,
        0.0, 0.0, 0.0, 1.0
    );
}

mat4 y_rotation(float rads)
{
    float c = cos(rads);
    float s = sin(rads);

    return mat4(
        c,   0.0, -s,  0.0,
        0.0, 1.0, 0.0, 0.0,
        s,   0.0, c,   0.0,
        0.0, 0.0, 0.0, 1.0
    );
}

//
// ===================
// Actual Shader Stuff
// ===================
//

/**
 * An array containing the path fraction for each vertex in the patch, as
 * generated in the vertex shader and passed through the TCS.
 */
in  float tcs_path_fraction[];
/**
 * The path fraction of the vertex generated by this iteration of the
 * Tessellation Evaluation Shader, interpolated over the Bezier curve.
 */
out float tes_path_fraction;

uniform float TIME_SECS = 0;

float cubic_bezier_float(float F0, float F1, float F2, float F3, float t)
{
    float u = 1.0 - t;

    return
        F0 * 1.0 * u*u*u +
        F1 * 3.0 * u*u*t +
        F2 * 3.0 * u*t*t +
        F3 * 1.0 * t*t*t ;
}

vec4 cubic_bezier_vec4(vec4 V0, vec4 V1, vec4 V2, vec4 V3, float t)
{
    float u = 1.0 - t;

    return
        V0 * 1.0 * u*u*u +
        V1 * 3.0 * u*u*t +
        V2 * 3.0 * u*t*t +
        V3 * 1.0 * t*t*t ;
}

void main()
{
    // Pass-through tessellation: draw straight polyline segments between the
    // patch control points instead of evaluating a Bezier curve.

    /**
     * The parameterised [0,1] position of this yet-to-be generated vertex,
     * generated by the Tesselation Primitive Generator.
     *
     * This should be interpreted as "fraction along the Bezier curve" for the
     * vertex generated in this iteration of the TES.
     */
    float t = gl_TessCoord.x;

    // Bezier curve interpolation
    vec4 bezier_position = cubic_bezier_vec4(
        gl_in[0].gl_Position,
        gl_in[1].gl_Position,
        gl_in[2].gl_Position,
        gl_in[3].gl_Position,
        t);

    // Path fraction interpolation
    float bezier_fraction = cubic_bezier_float(
        tcs_path_fraction[0],
        tcs_path_fraction[1],
        tcs_path_fraction[2],
        tcs_path_fraction[3],
        t);
    tes_path_fraction = bezier_fraction;

    //
    // Tranform the vertex to its final position in clip space
    //

    float pi = 3.1415926;
    float tau = 2.0 * pi;
    float PITCH_RADS = tau * 0.125;
    float ASPECT_RATIO = 1.7777;
    float ROTATION_RADS_PER_SEC = tau * - ( 2 / CYCLE_TIME_SECS ); // Rotate twice per cycle
    float FOV_RADS = tau * 0.25;
    float y_rads = TIME_SECS * ROTATION_RADS_PER_SEC;

    gl_Position = //
        perspective(FOV_RADS, ASPECT_RATIO, 0.1, 100.0)
      * translate(vec3(0.0, 0.0, -2))
      * x_rotation(PITCH_RADS)
      * y_rotation(y_rads)
      * bezier_position;
}