#version 460 core

layout(isolines, equal_spacing, cw) in;

in  float tcs_path_fraction[];
out float tes_path_fraction;

float cubicBezierFloat(float F0, float F1, float F2, float F3, float t)
{
    float u = 1.0 - t;

    return
        F0 * 1.0 * u*u*u +
        F1 * 3.0 * u*u*t +
        F2 * 3.0 * u*t*t +
        F3 * 1.0 * t*t*t ;
}

vec4 cubicBezierVec4(vec4 V0, vec4 V1, vec4 V2, vec4 V3, float t)
{
    float u = 1.0 - t;

    return
        V0 * 1.0 * u*u*u +
        V1 * 3.0 * u*u*t +
        V2 * 3.0 * u*t*t +
        V3 * 1.0 * t*t*t ;
}

void main()
{
    // Need to interpolate this too!! Maybe add to the bezier function?
    // tes_path_fraction = tcs_path_fraction;

    //
    // Parametric coordinate generated by tessellator
    //
    float t = gl_TessCoord.x;

    //
    // Evaluate cubic Bézier curve
    //
    gl_Position = cubicBezierVec4(
        gl_in[0].gl_Position,
        gl_in[1].gl_Position,
        gl_in[2].gl_Position,
        gl_in[3].gl_Position,
        t);
    
    tes_path_fraction = cubicBezierFloat(
        tcs_path_fraction[0],
        tcs_path_fraction[1],
        tcs_path_fraction[2],
        tcs_path_fraction[3],
        t);
}